name: Golang Test

on:
  pull_request:
    paths:
      - 'app/**/*.go'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: test
        run: go test -v ./...
