name: Golang Test

on:
  pull_request:
    paths:
      - 'app/**/*.go'

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0.28
        container_name: db
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: go_restapi_practice_test
          TZ: 'Asia/Tokyo'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Install dependencies
        working-directory: ./app
        run: go mod tidy

      - name: Setup test
        run: |
          sudo mkdir /app
          sudo cp ./app/config.ini /app/config.ini

      - name: Build
        working-directory: ./app
        run: go build -v ./...

      - name: test
        working-directory: ./app
        run: go test -v ./...
